import os

def make_page(path, title, meta_desc, h1, parent_name, parent_link, rel, content_html):
    nav = f"""  <div class="top-bar"><div class="container"><div class="top-bar-left"><span>&#128197; 24/7 Emergency Service</span><span>&#127757; Metro Vancouver</span></div><div class="top-bar-right"><a href="{rel}rebates.html" style="color:#4ade80;font-weight:600;">&#127383; Rebates Available</a></div></div></div>
  <header class="site-header"><div class="container"><nav class="navbar">
    <a href="{rel}index.html" class="logo"><div class="logo-icon">&#10052;</div><div class="logo-text"><strong>AceComfort</strong><span>Heating &amp; Air Conditioning</span></div></a>
    <ul class="nav-menu" id="navMenu">
      <li class="nav-item"><a href="{rel}index.html" class="nav-link">Home</a></li>
      <li class="nav-item"><a href="{rel}heating/index.html" class="nav-link">Heating</a></li>
      <li class="nav-item"><a href="{rel}air-conditioning/index.html" class="nav-link">Air Conditioning</a></li>
      <li class="nav-item"><a href="{rel}heat-pumps/index.html" class="nav-link">Heat Pumps</a></li>
      <li class="nav-item"><a href="{rel}air-duct-cleaning/index.html" class="nav-link">Air Duct Cleaning</a></li>
      <li class="nav-item"><a href="{rel}membership.html" class="nav-link">Membership</a></li>
      <li class="nav-item"><a href="{rel}rebates.html" class="nav-link">Rebates</a></li>
      <li class="nav-item"><a href="{rel}contact.html" class="nav-link">Contact Us</a></li>
    </ul>
    <div class="nav-cta"><a href="tel:6045550100" class="nav-phone">&#128222; (604) 555-0100</a><a href="{rel}contact.html" class="btn btn-primary btn-sm">Book Service</a><button class="menu-toggle" id="menuToggle" aria-label="Toggle menu"><span></span><span></span><span></span></button></div>
  </nav></div></header>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title} | AceComfort Vancouver BC</title>
  <meta name="description" content="{meta_desc}" />
  <link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;800&family=Open+Sans:wght@400;500;600&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="{rel}css/style.css" />
</head>
<body>
{nav}
  <section class="page-hero"><div class="container"><ul class="breadcrumb"><li><a href="{rel}index.html">Home</a></li><li><a href="{parent_link}">{parent_name}</a></li><li>{h1}</li></ul><h1>{h1} in Vancouver, BC</h1><p>{meta_desc}</p></div></section>
  <section class="section"><div class="container">
    {content_html}
    <div style="margin-top:2.5rem;display:flex;gap:1rem;flex-wrap:wrap;"><a href="{rel}contact.html" class="btn btn-primary btn-lg">Get a Free Quote</a><a href="tel:6045550100" class="btn btn-outline btn-lg">&#128222; (604) 555-0100</a></div>
  </div></section>
  <section class="cta-section"><div class="container"><h2>Book Your {h1} Service Today</h2><p>Professional service across Metro Vancouver. Call or request a quote online. Same-day service available.</p><div style="display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;"><a href="{rel}contact.html" class="btn btn-secondary btn-lg">Get a Free Quote</a><a href="tel:6045550100" class="btn btn-lg" style="background:#fff2;color:#fff;border:2px solid rgba(255,255,255,0.5);">&#128222; (604) 555-0100</a></div></div></section>
  <footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><a href="{rel}index.html" class="logo" style="margin-bottom:1rem;"><div class="logo-icon">&#10052;</div><div class="logo-text"><strong style="color:#fff;">AceComfort</strong><span style="color:rgba(255,255,255,0.5);">Heating &amp; Air Conditioning</span></div></a><p>Metro Vancouver HVAC experts. Licensed, insured, 24/7.</p></div><div class="footer-col"><h4>Services</h4><ul><li><a href="{rel}heating/index.html">Heating</a></li><li><a href="{rel}air-conditioning/index.html">Air Conditioning</a></li><li><a href="{rel}heat-pumps/index.html">Heat Pumps</a></li><li><a href="{rel}air-duct-cleaning/index.html">Duct Cleaning</a></li></ul></div><div class="footer-col"><h4>Company</h4><ul><li><a href="{rel}about.html">About</a></li><li><a href="{rel}membership.html">Membership</a></li><li><a href="{rel}rebates.html">Rebates</a></li><li><a href="{rel}contact.html">Contact</a></li></ul></div><div class="footer-col"><h4>Contact</h4><div class="footer-contact-item">&#128222; <a href="tel:6045550100" style="color:#fff;">(604) 555-0100</a></div></div></div></div><div class="footer-bottom"><div class="container"><span>&copy; 2025 AceComfort Heating &amp; Air Conditioning</span></div></div></footer>
  <div class="floating-cta"><a href="tel:6045550100" class="float-btn emergency">&#128222; <span class="label">Emergency: (604) 555-0100</span></a><a href="{rel}contact.html" class="float-btn">&#128197; <span class="label">Book Service</span></a></div>
  <script src="{rel}js/main.js"></script>
</body></html>"""

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f"Created: {path}")

base = r"C:\Users\ryans\acecomfort-website"

pages = [
    (f"{base}/heating/boilers.html", "Boiler Installation & Repair Vancouver BC",
     "Expert boiler installation, repair and servicing in Vancouver BC. Residential and commercial boilers, hydronic systems, and radiant heating. Call AceComfort (604) 555-0100.",
     "Boiler Installation & Service", "Heating", "../heating/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>Vancouver Boiler Specialists</h2><p>Boilers provide some of the most comfortable, consistent heat available. Radiant warmth heats evenly from the floor up with no dry air, no blowing dust, and no noise. AceComfort installs and services all types of residential and commercial boilers across Metro Vancouver.</p><p>From older cast-iron units to modern condensing boilers running at 95 percent efficiency and above, our certified technicians understand hydronic systems inside and out. We service Navien, Viessmann, Bosch, Weil-McLain, IBC, and all other major brands.</p><p>High-efficiency condensing boilers qualify for FortisBC rebates. We assess your system and identify every available incentive before recommending an upgrade path.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Our Boiler Services</h3><ul class='service-list'><li>New Boiler Installation</li><li>Emergency Boiler Repair</li><li>Annual Boiler Servicing</li><li>Hydronic System Design</li><li>Radiant Floor Heating Integration</li><li>Zone Control System Installation</li><li>Expansion Tank and Pressure Relief Service</li></ul></div></div></div>"),

    (f"{base}/heating/hot-water-tanks.html", "Hot Water Tank Replacement Vancouver BC",
     "Same-day hot water tank replacement and repair in Vancouver BC. Gas and electric options. Heat pump water heaters available. Emergency service. Call AceComfort (604) 555-0100.",
     "Hot Water Tank Replacement & Repair", "Heating", "../heating/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>Same-Day Hot Water Tank Service in Metro Vancouver</h2><p>A failing hot water tank rarely gives much warning. Whether yours has started leaking, run out of hot water unexpectedly, or simply reached the end of its service life, AceComfort provides same-day tank replacement across Metro Vancouver.</p><p>We carry the most popular tank sizes on our trucks and can typically have your new unit installed and delivering hot water within a few hours of your call. We handle Bradford White, A.O. Smith, Rheem, and all other major brands.</p><p>Considering upgrading to a tankless system or a heat pump water heater? We will walk you through the honest pros and cons for your household size and usage, factor in available rebates, and help you make the most financially sound decision.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Signs Your Tank Needs Attention</h3><ul class='service-list'><li>Rust or discolouration in hot water</li><li>Insufficient or no hot water</li><li>Visible tank leaking or pooling water</li><li>Loud popping or rumbling sounds</li><li>Tank is 10 or more years old</li><li>Noticeably rising energy bills</li></ul></div></div></div>"),

    (f"{base}/heating/tankless.html", "Tankless Water Heater Installation Vancouver BC",
     "Navien, Rinnai, and Bosch tankless water heater installation and service in Vancouver BC. Endless hot water on demand. FortisBC rebates available. Call AceComfort (604) 555-0100.",
     "Tankless Water Heater Installation", "Heating", "../heating/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>Endless Hot Water. Lower Energy Bills.</h2><p>Tankless water heaters heat water only when you need it, eliminating the standby heat loss of a traditional storage tank. The result is endless hot water and energy savings of up to 40 percent compared to a conventional tank.</p><p>AceComfort installs and services all leading tankless brands including Navien, Rinnai, Bosch, and Noritz. We handle all gas line and venting work for a fully code-compliant installation. FortisBC offers rebates for qualifying tankless upgrades and we manage the application on your behalf.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Tankless Services</h3><ul class='service-list'><li>Tankless Unit Installation</li><li>Gas Line Sizing and Upgrade</li><li>Venting and Exhaust Installation</li><li>Annual Flush and Descaling Service</li><li>Error Code Diagnostics and Repair</li><li>FortisBC Rebate Application</li></ul></div></div></div>"),

    (f"{base}/heating/combi-boiler.html", "Combi Boiler Installation Vancouver BC",
     "Combi boiler installation and service in Vancouver BC. One unit for space heating and domestic hot water. Space-saving and 95 percent efficient. Call AceComfort (604) 555-0100.",
     "Combi Boiler Installation & Service", "Heating", "../heating/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>One Compact Unit for Heating and Hot Water</h2><p>A combination boiler is a single, highly efficient unit that provides both central heating and domestic hot water with no separate storage tank needed. It is the ideal solution for Vancouver condos, smaller homes, and any space where mechanical room square footage is limited.</p><p>AceComfort installs and services combi boilers from Navien, IBC, Bosch, and Baxi. We integrate them with radiant floor heating, panel radiators, and fan coils, and handle all required gas and plumbing work. Modern condensing combi boilers operate at efficiencies of 95 percent and above.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Why Choose a Combi Boiler</h3><ul class='service-list'><li>No separate hot water tank required</li><li>Saves valuable mechanical room space</li><li>95 percent plus efficiency ratings</li><li>Instant on-demand hot water</li><li>Works with radiant floors and radiators</li><li>Qualifies for FortisBC rebates</li></ul></div></div></div>"),

    (f"{base}/heating/rooftop.html", "Rooftop HVAC Unit Installation Vancouver BC",
     "Commercial rooftop HVAC unit installation, maintenance, and repair in Vancouver BC. Packaged heating and cooling systems. Maintenance contracts available. Call AceComfort (604) 555-0100.",
     "Rooftop Unit Installation & Service", "Heating", "../heating/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>Commercial Rooftop HVAC Solutions</h2><p>Packaged rooftop units are the backbone of commercial HVAC across Metro Vancouver, used in offices, retail stores, restaurants, schools, and light industrial facilities. These self-contained systems provide both heating and cooling from a single rooftop installation.</p><p>AceComfort installs, maintains, and repairs all major brands including Carrier, Lennox, Trane, Daikin, and York. We offer preventive maintenance contracts that keep your rooftop units running at peak performance year-round and reduce the risk of costly emergency breakdowns.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Rooftop Unit Services</h3><ul class='service-list'><li>Rooftop Unit Installation</li><li>Emergency Commercial Repair</li><li>Preventive Maintenance Contracts</li><li>Controls and Thermostat Upgrades</li><li>Economizer Service and Repair</li><li>Refrigerant Leak Detection</li></ul></div></div></div>"),

    (f"{base}/heating/unit-heaters.html", "Unit Heater Installation Vancouver BC",
     "Gas-fired and electric unit heater installation and service in Vancouver BC. Ideal for warehouses, garages, and commercial spaces. Licensed installation to BC code. Call AceComfort (604) 555-0100.",
     "Unit Heater Installation & Service", "Heating", "../heating/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>Powerful Targeted Heat for Commercial and Industrial Spaces</h2><p>Unit heaters are the practical, cost-effective solution for heating large open spaces including warehouses, garages, auto shops, manufacturing facilities, and agricultural buildings that do not have ductwork or require supplemental heat in specific zones.</p><p>AceComfort installs and services both gas-fired and electric unit heaters across Metro Vancouver. We handle all gas line work, venting, and electrical connections, ensuring every installation meets BC building code requirements.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Applications We Serve</h3><ul class='service-list'><li>Warehouses and Distribution Centers</li><li>Auto and Mechanical Shops</li><li>Garages and Carports</li><li>Agricultural and Farm Buildings</li><li>Industrial and Manufacturing Spaces</li><li>Churches and Assembly Spaces</li></ul></div></div></div>"),

    # AC sub-pages
    (f"{base}/air-conditioning/central.html", "Central Air Conditioning Installation Vancouver BC",
     "Central AC installation, repair, and maintenance in Vancouver BC. Whole-home cooling using existing ductwork. All major brands. Same-day service. Call AceComfort (604) 555-0100.",
     "Central Air Conditioning", "Air Conditioning", "../air-conditioning/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>Whole-Home Cooling with Central Air Conditioning</h2><p>Central air conditioning is the most effective way to cool an entire home evenly and quietly. Using your existing forced-air ductwork, a central AC system connects to your furnace blower and delivers cool air to every room through the same vents your heating system uses.</p><p>AceComfort installs, repairs, and services central air conditioning from Carrier, Lennox, Trane, Napoleon, and more. We size every system correctly for your home, which is critical for efficiency, comfort, and equipment longevity. An oversized unit cools too quickly without removing humidity. An undersized unit runs constantly and cannot keep up on the hottest days.</p><p>Spring is the ideal time to install or service your central AC. Book early to beat the summer rush and be fully prepared when Vancouver heat arrives.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Central AC Services</h3><ul class='service-list'><li>New Central AC Installation</li><li>AC System Repair and Diagnostics</li><li>Seasonal Tune-Up and Maintenance</li><li>Refrigerant Check and Recharge</li><li>Coil Cleaning and Inspection</li><li>Thermostat and Controls Upgrade</li><li>System Efficiency Assessment</li></ul></div></div></div>"),

    (f"{base}/air-conditioning/ductless.html", "Ductless Air Conditioning Vancouver BC",
     "Ductless mini-split air conditioning installation and service in Vancouver BC. No ductwork required. Mitsubishi, Daikin, and more. Single and multi-zone systems. Call AceComfort (604) 555-0100.",
     "Ductless Air Conditioning", "Air Conditioning", "../air-conditioning/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>Flexible Cooling Without the Ductwork</h2><p>Ductless mini-split air conditioners are the ideal cooling solution for Vancouver homes without existing ductwork, for additions and new spaces, or for anyone who wants room-by-room temperature control without major renovation work.</p><p>A mini-split system consists of a compact outdoor unit connected by refrigerant lines to one or more indoor wall-mounted units. Each indoor unit operates independently, allowing different temperatures in different rooms. AceComfort installs and services ductless systems from Mitsubishi Electric, Daikin, Carrier, and LG. Many models double as heat pumps, providing both cooling in summer and efficient heating in winter.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Ductless AC Services</h3><ul class='service-list'><li>Single-Zone Mini-Split Installation</li><li>Multi-Zone System Installation</li><li>Ductless AC Repair and Service</li><li>Annual Filter and Coil Cleaning</li><li>Refrigerant Line Set Installation</li><li>Wall, Floor, and Ceiling Cassette Options</li></ul></div></div></div>"),

    # Heat pump sub-pages
    (f"{base}/heat-pumps/central.html", "Central Heat Pump Installation Vancouver BC",
     "Central heat pump installation and service in Vancouver BC. Whole-home heating and cooling using existing ductwork. Up to $10,000 in BC rebates available. Call AceComfort (604) 555-0100.",
     "Central Heat Pump Installation", "Heat Pumps", "../heat-pumps/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>Whole-Home Comfort with a Central Heat Pump</h2><p>A central heat pump is the most complete upgrade you can make to your home's comfort system. Using your existing ductwork, it replaces both your furnace and central air conditioner with a single, highly efficient system that heats in winter and cools in summer at up to three times the efficiency of electric resistance heating.</p><p>For Vancouver homeowners with existing forced-air systems, a central heat pump installation is often the most cost-effective upgrade path. You leverage the ductwork you already have, and the equipment cost is significantly offset by BC Hydro, CleanBC, and Canada Greener Homes rebates. AceComfort installs central heat pumps from Carrier, Lennox, Trane, and other leading manufacturers and handles every rebate application on your behalf.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Central Heat Pump Services</h3><ul class='service-list'><li>Central Heat Pump Installation</li><li>Ducted System Repair and Service</li><li>Dual-Fuel System Configuration</li><li>Ductwork Assessment and Modification</li><li>Thermostat and Smart Controls</li><li>Rebate Application Assistance</li></ul></div></div></div>"),

    (f"{base}/heat-pumps/ductless.html", "Ductless Heat Pump Installation Vancouver BC",
     "Ductless heat pump installation and service in Vancouver BC. Mitsubishi, Daikin, and Carrier mini-split systems. Heat and cool without ductwork. Rebates up to $10,000. Call (604) 555-0100.",
     "Ductless Heat Pump Installation", "Heat Pumps", "../heat-pumps/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>BC Most Popular Home Comfort Upgrade</h2><p>Ductless heat pumps are the fastest-growing home comfort solution in British Columbia. A ductless heat pump provides efficient heating and cooling with no ductwork required, making it the ideal upgrade for older Vancouver homes, condos, additions, or any space that needs targeted comfort control.</p><p>These systems use a small outdoor unit connected by refrigerant lines to one or more indoor wall units. Each indoor head operates independently. In winter, they extract heat from outdoor air and deliver it inside. In summer, they reverse to act as an air conditioner. Modern cold-climate models from Mitsubishi Electric and Daikin operate efficiently down to minus 25 degrees Celsius and are the number one rebate-qualifying upgrade through BC Hydro and CleanBC.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Ductless Heat Pump Services</h3><ul class='service-list'><li>Single and Multi-Zone Installation</li><li>Ductless Heat Pump Repair</li><li>Seasonal Maintenance Service</li><li>BC Hydro Rebate Applications</li><li>CleanBC Program Processing</li><li>Cold-Climate Models Available</li></ul></div></div></div>"),

    (f"{base}/heat-pumps/water-source.html", "Water Source Heat Pump Installation Vancouver BC",
     "Water source heat pump installation and service in Vancouver BC. Ideal for strata buildings, commercial properties, and multi-unit residential. High efficiency. Call AceComfort (604) 555-0100.",
     "Water Source Heat Pump Installation", "Heat Pumps", "../heat-pumps/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>High-Efficiency Heating for Strata and Commercial Buildings</h2><p>Water source heat pumps use a shared water loop system to deliver highly efficient heating and cooling to individual suites or zones. They are the standard choice for strata buildings, high-rise residential towers, hotels, and commercial properties throughout Metro Vancouver.</p><p>Unlike air-source heat pumps, water source systems exchange heat with a circulating water loop that maintains more consistent temperatures year-round, resulting in very high efficiency ratings and extremely quiet, reliable operation. AceComfort installs, repairs, and maintains water source systems for strata corporations, property managers, and commercial building owners.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Water Source HP Services</h3><ul class='service-list'><li>Individual Unit Installation and Replacement</li><li>Emergency Repair Service</li><li>Strata Building Maintenance Contracts</li><li>Water Loop System Servicing</li><li>Controls and Thermostat Replacement</li><li>Energy Efficiency Assessments</li></ul></div></div></div>"),

    # Air duct cleaning sub-pages
    (f"{base}/air-duct-cleaning/residential.html", "Residential Air Duct Cleaning Vancouver BC",
     "Professional residential air duct cleaning in Vancouver BC. Remove dust, allergens, and mold from your home duct system. Improve air quality and HVAC efficiency. Call AceComfort (604) 555-0100.",
     "Residential Air Duct Cleaning", "Air Duct Cleaning", "../air-duct-cleaning/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>Cleaner Air Starts with Clean Ducts</h2><p>Your home duct system is the respiratory system of your house. Every time your HVAC runs, it circulates air through every room. If those ducts contain years of accumulated dust, pet dander, mold spores, and allergens, that is exactly what your family breathes every day.</p><p>AceComfort uses professional-grade truck-mounted vacuum equipment and rotary brush systems to thoroughly clean your entire duct system. We clean every accessible section of supply and return ductwork, the air handler, and all registers and grilles. Most homes take 3 to 5 hours. We protect your flooring and furnishings throughout and leave your home in pristine condition.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Residential Cleaning Includes</h3><ul class='service-list'><li>All Supply and Return Duct Cleaning</li><li>Vent and Register Cleaning</li><li>Air Handler and Blower Cleaning</li><li>Evaporator Coil Inspection</li><li>Dryer Vent Cleaning Available</li><li>Optional Antimicrobial Treatment</li><li>Before and After Documentation</li></ul></div></div></div>"),

    (f"{base}/air-duct-cleaning/commercial.html", "Commercial Air Duct Cleaning Vancouver BC",
     "NADCA-standard commercial air duct cleaning in Vancouver BC. Offices, restaurants, schools, and multi-unit buildings. Maintenance contracts available. Call AceComfort (604) 555-0100.",
     "Commercial Air Duct Cleaning", "Air Duct Cleaning", "../air-duct-cleaning/index.html", "../",
     "<div class='grid-2' style='gap:3rem;'><div><h2>Commercial Duct Cleaning to NADCA Standards</h2><p>Commercial buildings accumulate contaminants in their HVAC systems at a far greater rate than residential homes. Higher occupancy, commercial cooking, renovation activities, and larger duct systems all contribute to faster buildup of dust, grease, mold, and other pollutants that compromise indoor air quality and system efficiency.</p><p>AceComfort performs commercial duct cleaning to NADCA standards across Metro Vancouver. We work around your operating schedule to minimize disruption, and we provide detailed documentation of all work completed. This is essential for health and safety compliance, insurance requirements, and property management records.</p></div><div><div style='background:var(--off-white);border:1px solid var(--border);border-radius:var(--radius-lg);padding:2rem;'><h3 style='margin-bottom:1.25rem;'>Commercial Applications</h3><ul class='service-list'><li>Office and Retail Buildings</li><li>Restaurants and Food Service</li><li>Schools and Childcare Centers</li><li>Medical and Dental Offices</li><li>Strata and Multi-Unit Residential</li><li>After-Construction Cleaning</li><li>Maintenance Contracts Available</li></ul></div></div></div>"),
]

for args in pages:
    make_page(*args)

print("All sub-pages created successfully!")
